// <auto-generated />
namespace GalleryCore.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.2-21211")]
    public sealed partial class change_Hash_length : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(change_Hash_length));
        
        string IMigrationMetadata.Id
        {
            get { return "201501301343071_change_Hash_length"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
